app/dashboard/forms.py
from flask.ext.wtf import Form
from wtforms import PasswordField, BooleanField, SubmitField
from wtforms_html5 import EmailField
from wtforms.validators import InputRequired, Length, Email, EqualTo, Optional


class SettingsForm(Form):
  email = EmailField('Change email', validators=[Optional(),Email()])
  password = PasswordField('New password', validators=[Optional(),
    Length(8, 64, message='Password must be more than 8 characters long.'),
    EqualTo('password2', message='Passwords must match ')])
  password2 = PasswordField('Password again', validators=[])

  receiveMail = BooleanField('Receive update mails')
  option1 = BooleanField('Option 1')
  option2 = BooleanField('Option 2')
  option3 = BooleanField('Option 3')

  passwordConfirm = PasswordField('Password confirmation', validators=[InputRequired(message="You must confirm with your current password"), Length(8, 64)])
  submit = SubmitField('Update')

app/dashboard/__init__.py
from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import views

app/dashboard/views.py
from flask import render_template, flash
from flask.ext.login import login_required, current_user

from ..email import send_email
from .. import db

from . import dashboard
from ..models import User
from .forms import SettingsForm


@dashboard.route('/', defaults={'path': ''}, methods=['GET', 'POST'])
@dashboard.route('/<path:path>', methods=['GET', 'POST'])
@login_required
def dash(path):
  form = SettingsForm()

  if form.validate_on_submit():
    if current_user.verify_password(form.passwordConfirm.data):
      if (form.password.data and form.password.data == form.password2.data and not current_user.verify_password(form.password.data)):
        # change password, not empty and password not same as old
        current_user.password = form.password.data
        db.session.add(current_user)
        flash('Your password has been updated.')
      if form.email.data and not form.email.data == current_user.email:
        # change email, not empty, not same,
        if User.query.filter_by(email=form.email.data).first():
          # email in use
          flash('Email already registered.')
        else:
          new_email = form.email.data
          token = current_user.generate_email_change_token(new_email)
          send_email(new_email, 'Confirm your email address',
                     'auth/mail/change_email',
                     user=current_user, token=token)
          flash('An email with instructions to confirm your new email '
                'address has been sent to you.')
    else:
      # entered wrong password
      flash("Wrong confirmation password")

  return render_template("dashboard/dashboard_" + current_user.readable_role() + ".html", form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/google.html" as google %}

{% block title %}DEVcoded{% endblock %}

{% block styles %}
<link href="{{ url_for('static', filename='css/styles.css') }}"  rel="stylesheet">
{{ super() }}

<!-- Fonts -->
<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Raleway:400,700'  rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700'  rel="stylesheet" type="text/css">

<!-- Animation -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.0/animate.min.css' rel="stylesheet" type="text/css">

{% endblock %}

{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='js/lib/jquery.nav.js') }}"></script>
<!-- Custom JS -->
<script src="{{ url_for('static', filename='js/main.js') }}"></script>

<!--{{google.analytics(account="")}}-->

{% endblock %}

app/templates/dashboard.html
{% extends "navbar_base.html" %}

{% block styles %}
    <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
    {{ super() }}
{% endblock %}

{% block content %}
<div class="container">
    <section class="overview" id="overview">

    </section>
</div>
{% endblock %}

app/templates/index.html
{% extends "navbar_base.html" %}

{% block styles %}
    <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
    {{ super() }}
{% endblock %}

{% block content %}
<img class="parallax-background" src="{{ url_for('static', filename='img/background.png') }}"></img>

<section class="home" id="home">
  <div class="container">
    <h1 class="intro">Quality products designed to enhance your server</h1>

    <div class="buttons">
      <a href="{{ url_for('main.order') }}" class="btn btn-primary custom-button green-btn">Order now</a>
    </div>
    <div class="row bottom-message-section">
      <div class="col-lg-4 col-sm-4">
        <div class="short-text">
          <i class="fa fa-dollar"></i> Packages to fit your budget
        </div>
      </div>
      <div class="col-lg-4 col-sm-4">
        <div class="short-text">
          <i class="fa fa-clock-o"></i> Fast turnaround
        </div>
      </div>
      <div class="col-lg-4 col-sm-4">
        <div class="short-text">
          <i class="fa fa-check"></i> Satisfaction guranteed
        </div>
      </div>
    </div>
  </div>
</section>

<section class="about-us" id="aboutus">
<div class="container">

  <div class="section-header">

    <h2 class="white-text">About US</h2>

    <h5 class="white-text">
        We are here for everything you need.
    </h5>
  </div>

  <div class="row">

    <div class="col-lg-4 col-md-4 column">
      <div class="big-intro">
          Plugins developed from the Core
      </div>
    </div>

    <div class="col-lg-4 col-md-4 column">
      <p>
          At DEVcoded we ensure that all of our plugins are designed with attention to detail from the core up.Thanks to our expert developers, we can guarantee high-quality design and optimized code for a great overall performance.
          <br/><br/>
          To meet your highest standards we follow a strict set of guidelines in the development of every plugin. Additionally, we know that communication with the client is key, and we do our best to keep you informed every step of the way. We strive to find new ways to solve your problems and deliver the best product available.
      </p>
    </div>

    <div class="col-lg-4 col-md-4 column">
      <ul class="skills">

        <li class="skill">
          <h6>Design</h6>
          <p>
            Thoughtfully put together to provide the best user experience.
          </p>
        </li>

        <li class="skill">
          <h6>Testing</h6>
          <p>
            Don’t worry about bugs. Every plugin is tested extensively prior to release.
          </p>
        </li>

        <li class="skill">
          <h6>Performance</h6>
          <p>
            Tuned to run with the lowest overhead possible.
          </p>
        </li>

      </ul>
    </div>
  </div>
</div>
</section>

<section class="testimonial" id="testimonials">
<div class="container">

        <div class="section-header">

    <h2 class="white-text">Testimonials</h2>

    <h6 class="white-text">
      We have many satisfied clients! Check what they're saying about us below.
    </h6>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div id="client-feedbacks">

      <div class="col-md-4">
        <div class="feedback-box">
          <div class="message">
             “Devcoded really helped jump start my minecraft server with their custom plugins."
          </div>
          <div class="client">
            <div class="quote red-text">
              <i class="fa fa-large fa-quote-left"></i>
            </div>
            <div class="client-info">
              <a class="client-name" href="">Patrick James</a>
              <div class="client-company">
                Owner FactionAction
              </div>
            </div>
            <div class="client-image">
              <img src="{{ url_for('static', filename='img/headshot1.png') }}" alt="">
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
       <div class="feedback-box">
          <div class="message">
             “Friendly people, helpful staff with great support, and awesome plugins."
          </div>
          <div class="client">
            <div class="quote green-text">
              <i class="fa fa-large fa-quote-left"></i>
            </div>
            <div class="client-info">
              <a class="client-name" href="">Michael Yates</a>
              <div class="client-company">
                Admin Parallax Servers
              </div>
            </div>
            <div class="client-image">
              <img src="{{ url_for('static', filename='img/headshot2.png') }}" alt="">
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="feedback-box">
          <div class="message">
             “Helped me get my servers up and running with custom plugins."
          </div>
          <div class="client">
            <div class="quote blue-text">
              <i class="fa fa-large fa-quote-left"></i>
            </div>
            <div class="client-info">
              <a class="client-name" href="">Alec Phillips</a>
              <div class="client-company">
                Owner MC-TNT
              </div>
            </div>
            <div class="client-image">
              <img src="{{ url_for('static', filename='img/headshot3.png') }}" alt="">
            </div>
          </div>
        </div>
      </div>

      </div>
    </div>
  </div>
</div>
</section>

<section class="features" id="features">
<div class="container">
 <div class="section-header">
    <h2 class="dark-text">Features</h2>
    <h6>
        We develop quality plugins to help your server, be it small or large.
    </h6>
  </div>

  <div class="row">

    <div class="col-md-6 col-sm-6">

      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-heart"></i>
        </div>
        <h5>Designed with Love</h5>
        <p>
            We’re passionate about creating the best plugins on the market.
            Everything that comes out of our business is held to the highest standards
        </p>
      </div>
      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-gears"></i>
        </div>
        <h5>Creative Features</h5>
        <p>
            If you can dream it, we can make it a reality!
        </p>
      </div>
      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-magic"></i>
        </div>
        <h5>Thousands of Options</h5>
        <p>
          Our pre-built plugin packages will get you up and running in no time at all. Choose from a set of options for a custom-tailored experience at a fraction of the price.
        </p>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-rocket"></i>
        </div>
        <h5>Easy to Customize</h5>
        <p>
          Our plugins are designed with server administrators in mind. Configurations are all well documented and flexible to the greatest extent.
        </p>
      </div>
      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-shield"></i>
        </div>
        <h5>Customer protection</h5>
        <p>
            All your data is securely stored in a private database for maximum security!
        </p>
      </div>
      <div class="feature">
        <div class="feature-icon">
          <i class="fa fa-large fa-trophy"></i>
        </div>
        <h5>Awesome Support</h5>
        <p>
            If you ever run into problems or are aren’t happy with our products, just let us know and we’ll make it right to you!
        </p>
      </div>
    </div>
  </div>
</div>
</section>

<section class="order" id="order">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3 class="white-text">Ready to order a plugin?</h3>
      </div>
      <div class="col-md-3">
        <a href="{{ url_for('main.order') }}" class="btn btn-lg custom-button blue-btn">Order now</a>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="pull-left">© 2014 DEVCoded</span>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-6">
        <span>Need to get in touch? Contact us at <a href="mailto:contact@devcoded.com">contact@devcoded.com</a></span>
      </div>
    </div>
  </div>
</footer>
{% endblock %}

app/templates/navbar_base.html
{% extends "base.html" %}

{% block navbar %}
<header class="header">
  <div id="main-nav" class="navbar navbar-inverse bs-docs-nav" role="navigation">
    <div class="container">
      <div class="navbar-header responsive-logo">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="./" class="navbar-brand">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="DEVcoded">
        </a>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
        <ul class="nav navbar-nav navbar-right responsive-nav main-nav-list">
          <li><a href="{{ url_for('main.index') }}#home">Home</a></li>
          <li><a href="{{ url_for('main.index') }}#aboutus">About Us</a></li>
          <li><a href="{{ url_for('main.index') }}#testimonials">Testimonials</a></li>
          <li><a href="{{ url_for('main.index') }}#features">Features</a></li>
          <li><a href={{ url_for('main.order') }}>Order</a></li>
          {% if current_user.is_authenticated() %}
              <li style="margin-left:40px"> <a href={{ url_for('dashboard.dash') }}>Dashboard</a></li>
              <li><a href={{ url_for('auth.logout') }}>Logout</a></li>
          {% else %}
             <li style="margin-left:40px"><a href={{ url_for('auth.login') }}>Login</a></li>
          {% endif %}
        </ul>
      </nav>
        <!-- Display flash messages directly under the navbar -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="animated bounceInLeft form-error-box" data-animation="bounceInLeft">
                    {% for message in messages %}
                        <span>{{ message }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
  </div>
</header>
{% endblock %}

app/templates/order.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/lib/timeline.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
  {%if messages %}
    {% for message in messages %}
      <span>{{ message }}</span>
    {% endfor %}
  {% endif %}
{% endwith %}

{% if form.errors %}
  {% for error in form.errors %}
    <span> {{ form.errors }} </span>
  {% endfor %}
{% endif %}

<div class="container">
  <div class="order-form-section">
    <div class="section-title">
      <h3 class="blue-text">Order a Plugin</h3>
      <h5>Be sure to include as much detail as possible.</h5>
    </div>
    <form action="{{ url_for('main.order') }}" method="POST">
      <div class="textbox-wrap clearfix"> <!-- SECTION: General -->
        <label for="plugin-name" class="control-label">Plugin name</label>
        <div class="col-md-4">
          <div class="input-group col-md-12">
            <span class="input-group-addon">
              <i class="fa fa-star"></i>
            </span>
            {{ form.plugin_name(id="plugin-name", class="form-control", required="required") }}
          </div>
        </div>
      </div>
      <div class="textbox-wrap">
        <label for="plugin-description" class="control-label">Plugin description</label>
        <div class="col-md-5">
          <div class="input-group col-md-12">
            {{ form.plugin_desc(id="plugin-description", class="form-control", rows="5") }}
          </div>
        </div>
      </div> <!-- END SECTION: General -->

      <div class="hr"></div>

      <div class="textbox-wrap"> <!-- SECTION: Commands -->
        <label>Commands</label>
        {{ form.commands() }}
        <div class="command-group clearfix">
          <div class="col-md-5">
            <div class="input-group col-md-12">
              <input required="required" id="commands-0-command_name" name="commands-0-command_name" class="form-control command-name" placeholder="/command [arg] [value]">
            </div>
          </div>
          <div class="col-md-3">
            <div class="input-group col-md-12">
              <input required="required" id="commands-0-command_perm" name="commands-0-command_perm" class="form-control command-permission" placeholder="permission.node">
            </div>
          </div>
          <div class="col-md-offset-3 col-md-8">
            <div class="input-group col-md-12">
              <input required="required" id="commands-0-command_desc" name="commands-0-command_desc" class="form-control" placeholder="Command description">
            </div>
          </div>
          <button disabled style="color: #ccc;" class="fa fa-large fa-minus-circle icon-button"></button>
        </div>

        <div class="col-md-12">
          <button id="mk-command" class="btn btn-success pull-right custom-button green-btn">
            <i class="fa fa-plus"></i>
          </button>
        </div>
      </div> <!-- END SECTION: Commands -->

      <div class="hr"></div>

      <div class="textbox-wrap"> <!-- SECTION: Permissions -->
        <label>Additional Permissions</label>
        <div class="command-group clearfix">
          <div class="col-md-3">
            <div class="input-group col-md-12">
              <input required="required" id="permissions-0-permission_name" name="permissions-0-permission_name" class="form-control" placeholder="permission.node">
            </div>
          </div>
          <div class="col-md-5">
            <div class="input-group col-md-12">
              <input required="required" id="permissions-0-permission_desc" name="permissions-0-permission_desc" class="form-control" placeholder="Permission description">
            </div>
          </div>
          <button disabled style="color: #ccc;" class="fa fa-large fa-minus-circle icon-button"></button>
        </div>
        <div class="col-md-12">
          <button id="mk-perm" class="btn btn-success pull-right custom-button green-btn">
            <i class="fa fa-plus"></i>
          </button>
        </div>
      </div> <!-- END SECTION: Permissions -->

      <div class="hr"></div>

      <div class="textbox-wrap"> <!-- SECTION: Configuration -->
        <label>Configuration</label>
        <div class="command-group clearfix">
          <div class="col-md-2">
            <div class="input-group col-md-12">
              <input required="required" id="configs-0-config_name" name="configs-0-config_name" class="form-control" placeholder="Name">
            </div>
          </div>
          <div class="col-md-2">
            <div class="input-group col-md-12">
              <input required="required" id="configs-0-config_val" name="configs-0-config_val" class="form-control" placeholder="Value">
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-group col-md-12">
              <input required="required" id="configs-0-config_desc" name="configs-0-config_desc" class="form-control" placeholder="Description">
            </div>
          </div>
          <button disabled style="color: #ccc;" class="fa fa-large fa-minus-circle icon-button"></button>
        </div>
        <div class="col-md-12">
          <button id="mk-config" class="btn btn-success pull-right custom-button green-btn">
            <i class="fa fa-plus"></i>
          </button>
        </div>
      </div> <!-- END SECTION: Configuration -->

      <div class="hr"></div>

      <div class="textbox-wrap clearfix"> <!-- SECTION: Events -->
        <label>Event Timeline</label>
        <ul style="margin-left:14%;" class="cbp_tmtimeline">
          <li style="margin-bottom: 0px;" class="command-group">
            <div class="cbp_tmicon">
              <button disabled class="fa fa-circle"></button>
            </div>
            <div class="cbp_tmlabel">
              <div class="input-group col-md-12">
                <input required="required" id="events-0-action" name="events-0-action" class="form-control" placeholder="Action (ie. command, event)">
              </div>
              <div class="hr"></div>
              <div class="input-group col-md-12">
                <input required="required" id="events-0-result" name="events-0-result" class="form-control" placeholder="Result (ie. what the plugin does)">
              </div>
            </div>
          </li>
          <li>
            <div class="cbp_tmicon cbp_add_tmlabel">
              <button id="mk-event" class="fa fa-plus"></button>
            </div>
          </li>
        </ul>
      </div> <!-- END SECTION: Events -->

      {{ form.csrf_token }}
      <div class="col-md-12 clearfix">
        <button type="submit" class="btn btn-success pull-right custom-button green-btn">Submit</button>
      </div>
    </form>
  </div>
</div>

<script id="command-template" type="text/x-jquery-tmpl">
<div class="command-group clearfix">
  <div class="col-md-offset-3 col-md-5">
    <div class="input-group col-md-12">
      <input required="required" id="commands-${idx}-command_name" name="commands-${idx}-command_name" class="form-control command-name" placeholder="/command [arg] [value]">
    </div>
  </div>
  <div class="col-md-3">
    <div class="input-group col-md-12">
      <input required="required" id="commands-${idx}-command_perm" name="commands-${idx}-command_perm" class="form-control command-permission" placeholder="permission.node">
    </div>
  </div>
  <div class="col-md-offset-3 col-md-8">
    <div class="input-group col-md-12">
      <input required="required" id="commands-${idx}-command_desc" name="commands-${idx}-command_desc" class="form-control" placeholder="Command description">
    </div>
  </div>
  <button class="fa fa-large fa-minus-circle icon-button rm-item"></button>
</div>
</script>

<script id="permission-template" type="text/x-jquery-tmpl">
<div class="command-group clearfix">
  <div class="col-md-offset-3 col-md-3">
    <div class="input-group col-md-12">
      <input id="permissions-${idx}-permission_name" name="permissions-${idx}-permission_name" class="form-control", placeholder="permission.node">
    </div>
  </div>
  <div class="col-md-5">
    <div class="input-group col-md-12">
      <input id="permissions-${idx}-permission_desc" name="permissions-${idx}-permission_desc" class="form-control", placeholder="Permission description">
    </div>
  </div>
  <button class="fa fa-large fa-minus-circle icon-button rm-item"></button>
</div>
</script>

<script id="configuration-template" type="text/x-jquery-tmpl">
<div class="command-group clearfix">
  <div class="col-md-offset-3 col-md-2">
    <div class="input-group col-md-12">
      <input required="required" id="configs-${idx}-config_name" name="configs-${idx}-config_name"class="form-control" placeholder="Name">
    </div>
  </div>
  <div class="col-md-2">
    <div class="input-group col-md-12">
      <input required="required" id="configs-${idx}-config_val" name="configs-${idx}-config_val" class="form-control" placeholder="Value">
    </div>
  </div>
  <div class="col-md-4">
    <div class="input-group col-md-12">
      <input required="required" id="configs-${idx}-config_desc" name="configs-${idx}-config_desc" class="form-control" placeholder="Description">
    </div>
  </div>
  <button class="fa fa-large fa-minus-circle icon-button rm-item"></button>
</div>
</script>

<script id="event-template" type="text/x-jquery-tmpl">
<li style="margin-bottom: 0px;" class="command-group">
  <div class="cbp_tmicon rm-event-buttons">
    <button class="fa fa-circle rm-item"></button>
  </div>
  <div class="cbp_tmlabel">
    <div class="input-group col-md-12">
      <input required="required" id="events-${idx}-action" name="events-${idx}-action" class="form-control input-lg" placeholder="Action (ie. command, event)">
    </div>
    <div class="hr"></div>
    <div class="input-group col-md-12">
      <input required="required" id="events-${idx}-result" name="events-${idx}-result" class="form-control input-lg" placeholder="Result (ie. what the plugin does">
    </div>
  </div>
</li>
<li>
</script>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/lib/jquery.tmpl.js') }}"></script>

<script>
function insertTemplateOnClick(button_id, template_id, dist) {
  $(button_id).on("click", function(e) {
    e.preventDefault(); // Don't submit on click
    var count = 1 + parseInt($(this).parents().eq(dist).siblings(".command-group").last().find("input").first().attr("id").replace(/[^\d.]/g, ""));
    if(isNaN(count)) { count = 1; };
    rendered_template = $(template_id).tmpl({idx: count});
    $(this).parents().eq(dist).siblings(".command-group").last().after( rendered_template );
  });
};

$(document).ready(function(){
  $(document).on("click", ".rm-item", function (e) {
    //[TODO]: Decrement idx of subsequent items
    e.preventDefault();
    $(this).closest(".command-group").remove();
  });

  $(document).on("keyup", ".command-name", function () {
    var clean_plugin_name = $("#plugin-name").val().split(" ")[0].toLowerCase().replace(/[^a-z0-9\s]/gi, '').replace(/[_\s]/g, '-');
    var clean_command_name = $(this).val().split(" ")[0].toLowerCase().replace(/[^a-z0-9\s]/gi, '').replace(/[_\s]/g, '-');

    var perm_ele = $(this).parents(':eq(1)').siblings(".col-md-3").children().children();
    $(perm_ele).val(clean_plugin_name + '.' + clean_command_name)
  });

  insertTemplateOnClick("#mk-command", "#command-template", 0);
  insertTemplateOnClick("#mk-perm", "#permission-template", 0);
  insertTemplateOnClick("#mk-config", "#configuration-template", 0);
  insertTemplateOnClick("#mk-event", "#event-template", 1);
});

</script>
{% endblock %}